name: Website Change Monitoring
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: nilp0inter/urlwatch-action@v1
        with:
          config-dir: '.github/urlwatch'
          cache-name: 'website-monitor-state'
