name: Monitor Upstream Releases
on:
  schedule:
    - cron: '10 10 * * *'  # Daily at 10:10
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        object:
          - tags
          - branches
        repo:
          - ctt-gob-es/clienteafirma
          - ctt-gob-es/clienteafirma-external
          - ctt-gob-es/jmulticard
    steps:
      - run: env
      - uses: nilp0inter/urlwatch-action@main
        with:
          cache-name: 'urlwatch-cache-${{ matrix.repo }}-${{ matrix.object }}'
          create-issue: true
          issue-header: 'New entry of type ${{ matrix.object }} in ${{ matrix.repo }}'
          issue-tags: 'upstream,update'
          token: ${{ secrets.GITHUB_TOKEN }}
          urls: |
            url: https://api.github.com/repos/${{ matrix.repo }}/${{ matrix.object }}
            filter:
              - jq: '.[] | .name'
              - sort:
