name: Monitor Upstream Releases
on:
  schedule:
    - cron: '10 10 * * *'  # Daily at 10:10
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: nilp0inter/urlwatch-action@c6c3195cc0f38420d84a4ec9ad541f9a25114baa # v0.0.2
        with:
          config-dir: '.github/urlwatch'
          cache-name: 'urlwatch-cache'
          create-issue: true
          issue-header: 'New official releases available 🎉'
          issue-tags: 'upstream,update'
          token: ${{ secrets.GITHUB_TOKEN }}
